// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Feed struct {
	ID            int32
	Title         pgtype.Text
	Description   pgtype.Text
	SiteLink      pgtype.Text
	FeedLink      string
	LastRefreshed pgtype.Timestamptz
}

type FeedItem struct {
	ID            int32
	EntryID       pgtype.Text
	Title         pgtype.Text
	Summary       pgtype.Text
	Link          string
	Content       pgtype.Text
	ItemUpdated   pgtype.Timestamptz
	ItemPublished pgtype.Timestamptz
	FeedID        int32
}

type User struct {
	ID       int32
	OauthSub string
	Email    string
	Name     string
}

type UserFeed struct {
	ID             int32
	UserID         int32
	FeedID         int32
	FeedName       string
	LastUpdated    pgtype.Timestamptz
	UpdateInterval pgtype.Interval
}

type UserFeedItem struct {
	ID     int32
	UserID int32
	ItemID int32
	IsRead pgtype.Bool
}
