// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/michaelcosj/pluto-reader/view/icon"

func Header() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"px-2\"><nav class=\"h-14 p-5 border-b border-text/10 flex items-center justify-between\"><div><a href=\"/\"><h1 class=\"md:text-xl\">Pluto Reader</h1></a></div><div class=\"flex items-center gap-5 py-2\"><button id=\"open-feed-modal-btn\" class=\"hidden md:inline-flex bg-primary text-background px-2 py-1.5 rounded-sm text-base\">Add Feed</button> <a href=\"/auth/logout\" class=\"text-white underline hover:font-bold text-sm md:text-base\">Log out</a></div></nav></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = addFeedModal().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func addFeedModal() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<dialog id=\"add-feed-modal\" class=\"relative px-8 py-12 bg-background shadow-md\"><p class=\"text-center font-medium text-lg pb-5\">Add New Feed</p><form method=\"post\" action=\"/feed/new\" class=\"flex flex-col gap-5 items-center\"><input type=\"text\" name=\"url\" placeholder=\"RSS/ATOM Url\" class=\"rounded px-5 py-3 border\"> <input type=\"text\" name=\"name\" placeholder=\"Feed Name\" class=\"rounded px-5 py-3 border\"> <button class=\"bg-primary text-background px-2 py-1.5 rounded-sm text-base\">Add Feed</button></form><button id=\"close-feed-modal-btn\" class=\"absolute top-1 right-1\" type=\"button\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icon.X().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button></dialog><script>\n        const feedModal = document.getElementById('add-feed-modal');\n        const openFeedModalBtn = document.getElementById('open-feed-modal-btn');\n        const closeFeedModalBtn = document.getElementById('close-feed-modal-btn');\n\n        openFeedModalBtn.addEventListener('click', () => {\n          feedModal.showModal();\n        });\n\n        closeFeedModalBtn.addEventListener('click', () => {\n          feedModal.close();\n        });\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
